$PROBLEM effect 
$DATA  dataEmax.csv  IGNORE=C
$INPUT C ID TIME DV MDV
$PRED

EM=THETA(1)*EXP(ETA(1))          
ET=THETA(2)*EXP(ETA(2))         

EFT=(EM*TIME)/(ET+TIME)
IPRED=EFT

Y=EFT*(1+ERR(1))

$THETA (30,150);EM
$THETA (0.01,0.5);ET50

$OMEGA 0.09
$OMEGA 0.09

$SIGMA 0.09

$ESTIMATION METHOD=1 INTER MAXEVAL=9990 PRINT=10 POSTHOC
$COVARIANCE
$TABLE ID TIME DV Y MDV CWRES
NOPRINT ONEHEADER FILE=Edata.txt