#type: ignore
class Warfarin(Module):

    def __init__(self) -> None:
        super().__init__()
        self.theta_V = theta(7.81)
        self.theta_Cl = theta(0.134)
        self.theta_ka = theta(0.571)
        self.theta_alag = theta(0.823)
        self.eta_Cl = omega(0.049)
        self.eta_V = omega(0.0802)
        self.eta_ka = omega(0.047)
        self.eta_alag = omega(0.156)
        self.eps_prop = sigma(0.0104)
        self.eps_add = sigma(0.554)
        data = pd.read_csv(pathlib.Path(__file__).parent.joinpath('warfarin.csv'))
        self.data = data[data['DVID'] == 1]
        self.dose = covariate(self.data['DOSE'])

    def pred(self, t: float) -> tuple[Expression, Expression]:
        alag = self.theta_alag * exp(self.eta_alag)
        alag__wrt_theta_V = 0
        alag__wrt_theta_Cl = 0
        alag__wrt_theta_ka = 0
        alag__wrt_theta_alag = __masmod__functional__exp(self.eta_alag)
        alag__wrt_eta_Cl = 0
        alag__wrt_eta_V = 0
        alag__wrt_eta_ka = 0
        alag__wrt_eta_alag = self.theta_alag * __masmod__functional__exp(self.eta_alag)
        alag__wrt_eps_prop = 0
        alag__wrt_eps_add = 0
        cl = self.theta_Cl * exp(self.eta_Cl)
        cl__wrt_theta_V = 0
        cl__wrt_theta_Cl = __masmod__functional__exp(self.eta_Cl)
        cl__wrt_theta_ka = 0
        cl__wrt_theta_alag = 0
        cl__wrt_eta_Cl = self.theta_Cl * __masmod__functional__exp(self.eta_Cl)
        cl__wrt_eta_V = 0
        cl__wrt_eta_ka = 0
        cl__wrt_eta_alag = 0
        cl__wrt_eps_prop = 0
        cl__wrt_eps_add = 0
        v = self.theta_V * exp(self.eta_V)
        v__wrt_theta_V = __masmod__functional__exp(self.eta_V)
        v__wrt_theta_Cl = 0
        v__wrt_theta_ka = 0
        v__wrt_theta_alag = 0
        v__wrt_eta_Cl = 0
        v__wrt_eta_V = self.theta_V * __masmod__functional__exp(self.eta_V)
        v__wrt_eta_ka = 0
        v__wrt_eta_alag = 0
        v__wrt_eps_prop = 0
        v__wrt_eps_add = 0
        ka = self.theta_ka * exp(self.eta_ka)
        ka__wrt_theta_V = 0
        ka__wrt_theta_Cl = 0
        ka__wrt_theta_ka = __masmod__functional__exp(self.eta_ka)
        ka__wrt_theta_alag = 0
        ka__wrt_eta_Cl = 0
        ka__wrt_eta_V = 0
        ka__wrt_eta_ka = self.theta_ka * __masmod__functional__exp(self.eta_ka)
        ka__wrt_eta_alag = 0
        ka__wrt_eps_prop = 0
        ka__wrt_eps_add = 0
        k = cl / v
        k__wrt_theta_V = -1 * self.theta_Cl * self.theta_V ** -2 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)
        k__wrt_theta_Cl = self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)
        k__wrt_theta_ka = 0
        k__wrt_theta_alag = 0
        k__wrt_eta_Cl = self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)
        k__wrt_eta_V = -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)
        k__wrt_eta_ka = 0
        k__wrt_eta_alag = 0
        k__wrt_eps_prop = 0
        k__wrt_eps_add = 0
        __bool_1 = alag > t
        __else__bool_1__ipred = 0
        __bool_1__ipred = 0
        if __bool_1:
            __bool_1__ipred = 0
        else:
            __else__bool_1__ipred = self.dose / v * ka / (ka - k) * (exp(-k * (t - alag)) - exp(-ka * (t - alag)))
        ipred = __bool_1 * __bool_1__ipred + (1 - __bool_1) * __else__bool_1__ipred
        ipred__wrt_theta_V = -1 * self.dose * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + -1 * self.dose * self.theta_Cl * self.theta_V ** -3 * self.theta_ka * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -2 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + self.dose * self.theta_Cl * self.theta_V ** -3 * self.theta_ka * (1 + -1 * __bool_1) * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) * __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))
        ipred__wrt_theta_Cl = self.dose * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -2 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + -1 * self.dose * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) * __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))
        ipred__wrt_theta_ka = self.dose * self.theta_V ** -1 * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + -1 * self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -2 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(2 * self.eta_ka) + self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(2 * self.eta_ka) * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka))
        ipred__wrt_theta_alag = self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * self.theta_ka * __masmod__functional__exp(self.eta_alag) * __masmod__functional__exp(self.eta_ka) * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_alag) * __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka)
        ipred__wrt_eta_Cl = self.dose * self.theta_Cl * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -2 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + -1 * self.dose * self.theta_Cl * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) * __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))
        ipred__wrt_eta_V = -1 * self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + -1 * self.dose * self.theta_Cl * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -2 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + self.dose * self.theta_Cl * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) * __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))
        ipred__wrt_eta_ka = self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + -1 * self.dose * self.theta_V ** -1 * self.theta_ka ** 2 * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -2 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(2 * self.eta_ka) + self.dose * self.theta_V ** -1 * self.theta_ka ** 2 * (1 + -1 * __bool_1) * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(2 * self.eta_ka) * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka))
        ipred__wrt_eta_alag = self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * self.theta_alag * self.theta_ka * __masmod__functional__exp(self.eta_alag) * __masmod__functional__exp(self.eta_ka) * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + self.theta_Cl * self.theta_V ** -1 * self.theta_alag * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_alag) * __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka)
        ipred__wrt_eps_prop = 0
        ipred__wrt_eps_add = 0
        y = ipred * (1 + self.eps_prop) + self.eps_add
        y__wrt_theta_V = -1 * self.dose * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + -1 * self.dose * self.theta_Cl * self.theta_V ** -3 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -2 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + self.dose * self.theta_Cl * self.theta_V ** -3 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) * __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))
        y__wrt_theta_Cl = self.dose * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -2 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + -1 * self.dose * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) * __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))
        y__wrt_theta_ka = self.dose * self.theta_V ** -1 * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + -1 * self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -2 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(2 * self.eta_ka) + self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(2 * self.eta_ka) * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka))
        y__wrt_theta_alag = self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * self.theta_ka * __masmod__functional__exp(self.eta_alag) * __masmod__functional__exp(self.eta_ka) * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_alag) * __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka)
        y__wrt_eta_Cl = self.dose * self.theta_Cl * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -2 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + -1 * self.dose * self.theta_Cl * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) * __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))
        y__wrt_eta_V = -1 * self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + -1 * self.dose * self.theta_Cl * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -2 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + self.dose * self.theta_Cl * self.theta_V ** -2 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * 2 * self.eta_V) * __masmod__functional__exp(self.eta_ka) * __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))
        y__wrt_eta_ka = self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka) + -1 * self.dose * self.theta_V ** -1 * self.theta_ka ** 2 * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -2 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(2 * self.eta_ka) + self.dose * self.theta_V ** -1 * self.theta_ka ** 2 * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(2 * self.eta_ka) * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka))
        y__wrt_eta_alag = self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (1 + self.eps_prop) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * self.theta_alag * self.theta_ka * __masmod__functional__exp(self.eta_alag) * __masmod__functional__exp(self.eta_ka) * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + self.theta_Cl * self.theta_V ** -1 * self.theta_alag * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_alag) * __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka)
        y__wrt_eps_prop = self.dose * self.theta_V ** -1 * self.theta_ka * (1 + -1 * __bool_1) * (self.theta_ka * __masmod__functional__exp(self.eta_ka) + -1 * self.theta_Cl * self.theta_V ** -1 * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V)) ** -1 * (-1 * __masmod__functional__exp(-1 * self.theta_ka * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_ka)) + __masmod__functional__exp(-1 * self.theta_Cl * self.theta_V ** -1 * (t + -1 * self.theta_alag * __masmod__functional__exp(self.eta_alag)) * __masmod__functional__exp(self.eta_Cl) * __masmod__functional__exp(-1 * self.eta_V))) * __masmod__functional__exp(-1 * self.eta_V) * __masmod__functional__exp(self.eta_ka)
        y__wrt_eps_add = 1
        return (ipred, y)